pipeline {
    agent any 
    satge('checkout'){
        steps{
            git url: https://github.com/vinitpatil05/DockerB3.git,branch main
        }
    }
stage('Build Image'){
steps{
bat 'docker build -t mywebsite .'
}
}
stage('3.Stop/Remove old containers'){
steps{
bat 'docker stop mycont || exit 0'
bat 'docker rm mycont|| exit 0'
}
}
stage('Run the Image- Containerize){
steps{
bat 'docker run -d -p 5000:80 --name mycont mywebsite'

}
}

}
}
